doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'

      vicidial:
        url: '%env(resolve:VICIDIAL_DATABASE_URL)%'
        server_version: 'mariadb-10.11.2'
        idle_connection_ttl: 0

      Datamart:
        url: '%env(resolve:DATAMART_DATABASE_URL)%'
        server_version: 'mariadb-10.11.2'

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    default_entity_manager: crm
    entity_managers:
      crm:
        connection: default
        mappings:
          CRM:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/CRM'
            prefix: 'App\Entity\CRM'
            alias: CRM

          GesdinetJWTRefreshTokenBundle:
            is_bundle: true