<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260328232955 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace crm_user relations with vicidial_user fields and rename task table to tasks';
    }

    public function up(Schema $schema): void
    {
        // 1. créer la nouvelle table tasks
        $this->addSql(<<<'SQL'
            CREATE TABLE tasks (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(255) NOT NULL,
                description TEXT DEFAULT NULL,
                dueDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                completed BOOLEAN NOT NULL,
                createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                status VARCHAR(255) NOT NULL,
                priority VARCHAR(255) NOT NULL,
                vicidial_user VARCHAR(50) DEFAULT NULL,
                appointment_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_50586597E5B533F9 ON tasks (appointment_id)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE tasks
            ADD CONSTRAINT FK_50586597E5B533F9
            FOREIGN KEY (appointment_id) REFERENCES appointment (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        // 2. supprimer d'abord les FK de l'ancienne table task
        $this->addSql(<<<'SQL'
            ALTER TABLE task DROP CONSTRAINT fk_527edb25e5b533f9
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE task DROP CONSTRAINT fk_f24c741b4b259f02
        SQL);

        // 3. supprimer les FK vers crm_users AVANT de drop la table crm_users
        $this->addSql(<<<'SQL'
            ALTER TABLE appointment DROP CONSTRAINT fk_78a477934b259f02
        SQL);

        $this->addSql(<<<'SQL'
            DROP INDEX idx_78a477934b259f02
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE note DROP CONSTRAINT fk_6f8f552a4b259f02
        SQL);

        $this->addSql(<<<'SQL'
            DROP INDEX idx_6f8f552a4b259f02
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE notification DROP CONSTRAINT fk_a765ad324b259f02
        SQL);

        $this->addSql(<<<'SQL'
            DROP INDEX idx_a765ad324b259f02
        SQL);

        // 4. modifier les tables CRM
        $this->addSql(<<<'SQL'
            ALTER TABLE appointment ADD vicidial_campaign_id VARCHAR(20) DEFAULT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE appointment DROP COLUMN crm_user_id
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE appointment ALTER COLUMN vicidial_user SET NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE note ADD vicidial_user VARCHAR(50) DEFAULT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE note DROP COLUMN crm_user_id
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE notification ADD vicidial_user VARCHAR(50) DEFAULT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE notification DROP COLUMN crm_user_id
        SQL);

        // 5. supprimer les anciennes tables à la fin
        $this->addSql(<<<'SQL'
            DROP TABLE task
        SQL);

        $this->addSql(<<<'SQL'
            DROP TABLE crm_users
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE crm_users (
                user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                username VARCHAR(255) NOT NULL,
                pass VARCHAR(255) NOT NULL,
                full_name VARCHAR(50) DEFAULT NULL,
                user_level SMALLINT DEFAULT NULL,
                PRIMARY KEY (user_id)
            )
        SQL);

        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_a88afad1f85e0677 ON crm_users (username)
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE task (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title VARCHAR(255) NOT NULL,
                description TEXT DEFAULT NULL,
                completed BOOLEAN NOT NULL,
                createdat TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                status VARCHAR(255) NOT NULL,
                priority VARCHAR(255) NOT NULL,
                crm_user_id INT NOT NULL,
                appointment_id INT NOT NULL,
                completedat TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                duedate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX idx_f24c741be5b533f9 ON task (appointment_id)
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX idx_f24c741b4b259f02 ON task (crm_user_id)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE task ADD CONSTRAINT fk_527edb25e5b533f9 FOREIGN KEY (appointment_id) REFERENCES appointment (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE task ADD CONSTRAINT fk_f24c741b4b259f02 FOREIGN KEY (crm_user_id) REFERENCES crm_users (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE tasks DROP CONSTRAINT FK_50586597E5B533F9
        SQL);

        $this->addSql(<<<'SQL'
            DROP TABLE tasks
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE appointment ADD crm_user_id INT NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE appointment DROP COLUMN vicidial_campaign_id
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE appointment ALTER COLUMN vicidial_user DROP NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE appointment ADD CONSTRAINT fk_78a477934b259f02 FOREIGN KEY (crm_user_id) REFERENCES crm_users (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX idx_78a477934b259f02 ON appointment (crm_user_id)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE note ADD crm_user_id INT NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE note DROP COLUMN vicidial_user
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE note ADD CONSTRAINT fk_6f8f552a4b259f02 FOREIGN KEY (crm_user_id) REFERENCES crm_users (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX idx_6f8f552a4b259f02 ON note (crm_user_id)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE notification ADD crm_user_id INT NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE notification DROP COLUMN vicidial_user
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE notification ADD CONSTRAINT fk_a765ad324b259f02 FOREIGN KEY (crm_user_id) REFERENCES crm_users (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX idx_a765ad324b259f02 ON notification (crm_user_id)
        SQL);
    }
}